### ISSUE TITLE
Can't extend plugin's properties without rewriting all of them

### ISSUE THREAD

**Issue by ghost** [benface/tailwindcss-transitions#8]
I'm using the latest version of tailwindcss and tailwindcss-transitions. 
When I use the `theme: { extend:{} }` syntax to add, as an example, a "margin" transitionProperty, the resulting compiled css will only contains the .transition-margin utility.

Example code:
`theme: { extend: { transitionProperty: { 'margin': 'margin' } } }`.

Am I doing something wrong? I'm using the same syntax for the core values of tailwindcss and it's working as intended by adding new values and replacing existing ones without deleting the other pre-existing ones.

**Comment by benface** [comment]
@cristiangervasi-aimage Thank you for reporting. Unfortunately this is not how Tailwind works at the moment; plugins don't have the ability to define a default theme that users can extend with `theme.extend`, which is really meant to be used with Tailwind's core plugins. There is no difference between adding the `transitionProperty` object to `theme` or `theme.extend` because Tailwind merges the former with the latter before the plugin has a chance to read it, and since there is no `transitionProperty` in the default Tailwind `theme`, there is nothing to extend.

It is kinda related to this issue, which I just posted in in reference to your (totally reasonable) expectations: https://github.com/tailwindcss/tailwindcss/issues/660#issuecomment-532477787

In the meantime, you can simply copy the default `transitionProperty` object into your config's `theme` and add whatever you want there, like this:

```
theme: {
  transitionProperty: {
    // default
    'none': 'none',
    'all': 'all',
    'color': 'color',
    'bg': 'background-color',
    'border': 'border-color',
    'colors': ['color', 'background-color', 'border-color'],
    'opacity': 'opacity',
    'transform': 'transform',

    // custom
    'margin': 'margin',
  },
}
```

I will close this for now, since it is working "as expected" given Tailwind's current API, but hopefully Tailwind provides a way to do this in the future.
